import type {Metadata} from "next";
import "./globals.css";

import {Inter, Prata} from "next/font/google";
import {Header} from "@/components/header";

// If loading a variable font, you don't need to specify the font weight
const prata = Prata({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prata",
  weight: "400",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prata.variable} ${inter.variable} antialiased bg-grey-200`}
      >
        <Header />
        <div className="bg-grey-200 screen w-full relative flex px-12 py-8">
          {children}
        </div>
      </body>
    </html>
  );
}
